version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    image: ghcr.io/kaganay/predictive-maintenance-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=PredictiveMaintenanceDb;Trusted_Connection=True;TrustServerCertificate=True;
    ports:
      - "5135:8080"
    depends_on:
      - rabbitmq
      - redis

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    image: ghcr.io/kaganay/predictive-maintenance-web:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5001:8080"
    depends_on:
      - api

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
